name: tesseract-ocr
channels:
  - conda-forge
dependencies:
  - tesseract
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - matplotlib
  - numba
  - numexpr
  - numpy
  - olefile
  - pip
  - pandas
  - pillow
  - plotly
  - pytesseract
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
    - jupyter-contrib-core
    - jupyter-contrib-nbextensions
    - jupyter-highlight-selected-word
    - jupyter-latex-envs
    - jupyter-nbextensions-configurator
    - opencv-python
