name: tesseract-ocr
channels:
  - conda-forge
dependencies:
  - tesseract
  - pytesseract
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyter-contrib-core
  - jupyter-contrib-nbextensions
  - jupyter-highlight-selected-word
  - jupyter-latex-envs
  - jupyter-nbextensions-configurator
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - matplotlib
  - numba
  - numexpr
  - numpy
  - olefile
  - opencv-python
  - pandas
  - pillow
  - plotly
  - pytesseract
  - scikit-image
  - scikit-learn
  - scipy
